task: classification #i.e. classification,segmentation,detection

#model: /home/seeking/llf/code/tensorRT-lab/temp/models/yolov8/yolov8n-cls-bs1.engine
#model: /home/seeking/llf/code/tensorRT-lab/temp/models/yolov8/yolov8n-cls-bs2.engine
#model: /home/seeking/llf/code/tensorRT-lab/temp/models/yolov8/yolov8n-cls-bs4.engine
model: /home/seeking/llf/code/tensorRT-lab/temp/models/yolov8/yolov8n-cls-dynamic.engine

images: /home/seeking/llf/code/tensorRT-lab/temp/images/imagenet
output: /home/seeking/llf/code/tensorRT-lab/yolo/output

labels_file: /home/seeking/llf/code/tensorRT-lab/imagenet_classes.txt
thr_file:

device: 0   # i.e. 0,1,2
mode: fp32  # i.e. fp32,fp16,int8
batch: 4    # if model is dynamic

input_shape: [ 3,224,224 ]

thr: [ 0.8,0.2 ]
labels: [ 0good,1bad ]
iou: 0.5
conf: 0.5

